[package]

name = "rustcql"
version = "0.0.4"
authors = ["Maxim Baranov <sprayrules@gmail.com>"]

description = "Rust Cassandra Client (CQL Binary Protocol v4)"
repository = "https://github.com/madmaxio/rustcql"
keywords = ["cassandra", "cql", "database", "driver"]
license = "MIT"


[dependencies]

bufstream = "0.1.2"
byteorder = "0.5.1"
uuid = "0.2.2"
serde = "0.7.4"
serde_json = "0.7.0"
serde_macros = "0.7.4"