[package]

name = "rustcql"
version = "0.0.1"
authors = ["Maxim Baranov <sprayrules@gmail.com>"]


keywords = ["cassandra", "cql", "database", "driver"]



[dependencies]

bufstream = "*"
byteorder = "*"
time = "*"
uuid = "*"